version: '3.8'
services:
  db:
    image: postgres:13
    container_name: monga-awards-db
    restart: always
    environment:
      POSTGRES_USER: mongauser
      POSTGRES_PASSWORD: mongapassword
      POSTGRES_DB: monga_awards
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
